# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :develop do
    build_app(
       scheme: "Demo02",
       export_method:"development",
       workspace: "Demo02.xcworkspace")
       pgyer(api_key: "a5997105d25880cb56fe41d37bc44a1e", user_key:"8af32dbce81546db5ce510d95e5841a9")
  end
end
